# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

  services:
    runner:
      # image: custom-github-runner-mac:latest
      build:
        context: ./
        dockerfile: Dockerfile
        args:
          - RUNNER_VERSION=2.323.0  # Removed the extra space
          - OS_ARCH=arm64 #arm64 or x64
      restart: always
      environment:
        - REPO=${REPO:-OpsLifeCycle}
        - REG_TOKEN=${REG_TOKEN}
        - NAME=${NAME:-1}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      deploy:
        mode: replicated
        replicas: 1
        resources:
          limits:
            cpus: "1"
            memory: 1G
          reservations:
            cpus: "0.5"
            memory: 512M