# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

# reference to the endpoint
name: green
endpoint_name: nlp-summarize-online

# compute
instance_type: Standard_D4as_v4
instance_count: 1

# model
model: azureml:pubmed-summarization@latest

# scoring code
code_configuration:
  code: ../../../../data-science/src/summarization/
  scoring_script: score.py

# custom scoring environment
environment: 
  conda_file: ../../../../data-science/environments/inference/conda_env.yml
  image: mcr.microsoft.com/azureml/minimal-ubuntu18.04-py37-cpu-inference:latest


liveness_probe: 
    period: 10
    initial_delay: 300
    timeout: 5
    success_threshold: 1
    failure_threshold: 3
readiness_probe: 
    period: 10
    initial_delay: 300
    timeout: 5
    success_threshold: 1
    failure_threshold: 3
