# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

name: 01-train-create-compute-pipeline

on: 
  workflow_dispatch:
    inputs:
      action_type:
        default: create
        description: 'Action Type'
        required: true
        type: choice
        options:
          - create
          - delete

jobs:
  set-env-branch:
    runs-on: ubuntu-24.04
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prd-branch
        name: set-prd-branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "config_env=config-infra-prd.yml" >> $GITHUB_ENV
      - id: set-dev-branch
        name: set-dev-branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "config_env=config-infra-dev.yml" >> $GITHUB_ENV
      - id: set-output-defaults
        name: set-output-defaults
        run: |
          echo "config-file=$config_env" >> $GITHUB_OUTPUT

  get-config:
    needs: set-env-branch
    uses: OpsLifeCycle/mlops/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file }}

  create-compute-standard:
    needs: [get-config]
    uses: OpsLifeCycle/mlops/.github/workflows/create-compute.yml@main
    with:
      cluster_name: cpu-cluster
      size: Standard_D2as_v4
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.ml_workspace }}
      action_type: ${{ inputs.action_type }}
    secrets:
      clientId: ${{ secrets.ARM_CLIENT_ID }}
      clientSecret: ${{ secrets.ARM_CLIENT_SECRET }}
      subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      tenantId: ${{ secrets.ARM_TENANT_ID }}

  create-batch-compute-standard:
    needs: [get-config]
    uses: OpsLifeCycle/mlops/.github/workflows/create-compute.yml@main
    with:
      cluster_name: batch-cluster
      size: Standard_D2as_v4
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.ml_workspace }}
      action_type: ${{ inputs.action_type }}
    secrets:
      clientId: ${{ secrets.ARM_CLIENT_ID }}
      clientSecret: ${{ secrets.ARM_CLIENT_SECRET }}
      subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      tenantId: ${{ secrets.ARM_TENANT_ID }}

  create-compute-large:
    needs: get-config
    uses: OpsLifeCycle/mlops/.github/workflows/create-compute.yml@main
    with:
      cluster_name: cpu-cluster-lg
      size: Standard_D16as_v4
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.ml_workspace }}
      action_type: ${{ inputs.action_type }}
    secrets:
      clientId: ${{ secrets.ARM_CLIENT_ID }}
      clientSecret: ${{ secrets.ARM_CLIENT_SECRET }}
      subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      tenantId: ${{ secrets.ARM_TENANT_ID }}
    
  create-batch-compute-large:
    needs: get-config
    uses: OpsLifeCycle/mlops/.github/workflows/create-compute.yml@main
    with:
      cluster_name: batch-cluster-lg
      size: Standard_D16as_v4
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.ml_workspace }}
      action_type: ${{ inputs.action_type }}
    secrets:
      clientId: ${{ secrets.ARM_CLIENT_ID }}
      clientSecret: ${{ secrets.ARM_CLIENT_SECRET }}
      subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      tenantId: ${{ secrets.ARM_TENANT_ID }}

  create-compute-gpu:
    needs: get-config
    uses: OpsLifeCycle/mlops/.github/workflows/create-compute.yml@main
    with:
      cluster_name: gpu-cluster
      size: Standard_NC4as_T4_v3
      cluster_tier: low_priority
      min_instances: 0
      max_instances: 4
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.ml_workspace }}
      action_type: ${{ inputs.action_type }}
    secrets:
      clientId: ${{ secrets.ARM_CLIENT_ID }}
      clientSecret: ${{ secrets.ARM_CLIENT_SECRET }}
      subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      tenantId: ${{ secrets.ARM_TENANT_ID }}
