# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0


steps:
  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group create --location $(location) --name $(terraform_st_resource_group)'