# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0


# Dev environment
variables:
  # Global
  environment: dev
  ap_vm_image: ubuntu-24.04

  #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  namespace: mlops
  postfix: 0001
  location: centralindia
  enable_aml_computecluster: true
  enable_monitoring: false
  terraform_version: 1.10.4
  infrastructure_provider: azure

  # # DO NOT TOUCH for reference only

  # # Azure DevOps reference only
  # ado_service_connection_rg: azure-arm-$(location)
  # ado_service_connection_aml_ws: azure-arm-$(location)


  # # For pipeline reference only
  # resource_group: rg-$(namespace)-$(environment)-$(postfix)
  # ml_workspace: mlw-$(namespace)-$(environment)-$(postfix)
  # application_insights: mlw-$(namespace)-$(environment)-$(postfix)
  # key_vault: kv-$(namespace)-$(environment)-$(postfix)
  # container_registry: cr$(namespace)$(environment)$(postfix)
  # storage_account: st$(namespace)$(environment)$(postfix)


  # terraform_st_location: $(location)
  # terraform_st_resource_group: rg-$(namespace)-$(environment)-tf-$(postfix)
  # terraform_st_storage_account: st$(namespace)$(environment)tf$(postfix)
  # terraform_st_container_name: ct-$(namespace)-$(environment)-tf-$(postfix)
  # terraform_st_key: keytab-$(namespace)-$(environment)-tf-$(postfix)
