name: azureml-cli-v2
channels:
  - conda-forge
  - defaults
dependencies:
  - pkg-config==0.29.2
  - python==3.9.21
  - yapf==0.43.0
  - pylint==3.3.3
  - pip==24.3.1
  - pip:
      - mlflow
      - cloudpickle==3.1.0
      - scikit-learn==1.6.1
      - flask==3.1.0
      - applicationinsights==0.11.10
      - pandas
      - azureml-core
      - azureml-dataset-runtime[fuse]
      - opencensus-ext-azure==1.1.14
