# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

# This is a workflow for Connecting to an AML Workspace
name: 10-Connect-to-Workspace
# Controls when the workflow will run
on: 
  workflow_call:
    inputs:
      resourceGroup:
        description: 'Resource Group'     
        required: true
        type: string
      workspace:
        description: 'Workspace Name'     
        required: true
        type: string
    secrets:
      clientId:
        required: true
      clientSecret:
        required: true
      tenantId:
        required: true
      subscriptionId:
        required: true    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "ConnectToWorkspace"
  ConnectToWorkspace:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.clientId }}","clientSecret":"${{ secrets.clientSecret }}","subscriptionId":"${{ secrets.subscriptionId }}","tenantId":"${{ secrets.tenantId }}"}'
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: list-models
        run:  az ml model list --resource-group ${{inputs.resourceGroup}} --workspace-name ${{inputs.workspace}}
        #run: az configure --defaults group=${{inputs.resourceGroup}} workspace=${{inputs.workspace}}
