# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

name: 07-create-endpoint

on:
  workflow_call:
    inputs:
      endpoint_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      endpoint_name:
        required: true
        type: string
      endpoint_type:
        required: true
        type: string
      action_type:  
        required: true
        type: string
    secrets:
      clientId:
        required: true
      clientSecret:
        required: true
      tenantId:
        required: true
      subscriptionId:
        required: true
jobs:
  create-endpoint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: "Az CLI login"
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.clientId }}","clientSecret":"${{ secrets.clientSecret }}","subscriptionId":"${{ secrets.subscriptionId }}","tenantId":"${{ secrets.tenantId }}"}'
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-endpoint-from-file
        if: ${{ inputs.action_type == 'create'}}
        run: |
          az ml ${{ inputs.endpoint_type }}-endpoint create \
          --name ${{ inputs.endpoint_name }} \
          -f ${{ github.workspace }}/${{ inputs.endpoint_file }} \
          --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }}
      - name: delete-endpoint
        if: ${{ inputs.action_type == 'delete'}}
        run: |
          az ml ${{ inputs.endpoint_type }}-endpoint delete \
          --name ${{ inputs.endpoint_name }} \
          --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }} \
          --no-wait \
          --yes