# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

name: 05-create-dataset

on:
  workflow_call:
    inputs:
      data_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      file_type:
        required: false
        type: string
        default: ""
      name:
        required: true
        type: string
    secrets:
      clientId:
        required: true
      clientSecret:
        required: true
      tenantId:
        required: true
      subscriptionId:
        required: true        
jobs:
  create-dataset:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: "Az CLI login"
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.clientId }}","clientSecret":"${{ secrets.clientSecret }}","subscriptionId":"${{ secrets.subscriptionId }}","tenantId":"${{ secrets.tenantId }}"}'
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-dataset-from-file
        if: ${{ inputs.file_type == ''}}
        run: |
          az ml data create \
          --file ${{ github.workspace }}/${{ inputs.data_file }} \
          --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }} \
          --name ${{ inputs.name }}
      - name: create-dataset-as-job
        if: ${{ inputs.file_type != ''}}
        run: |
          az ml job create \
          --file ${{ github.workspace }}/${{ inputs.data_file }} \
          --resource-group ${{ inputs.resource_group }} \
          --workspace-name ${{ inputs.workspace_name }}
