# Copyright (c) Rahul Bourai. All rights reserved.
# Licensed under the PolyForm Strict License 1.0.0

name: 03-create-compute

on: 
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:  
        required: true
        type: string
      min_instances: 
        required: true
        type: number
      max_instances: 
        required: true
        type: number
      resource_group:   
        required: true
        type: string
      workspace_name:  
        required: true
        type: string
      action_type:  
        required: true
        type: string
      cluster_tier: 
        required: false
        type: string
    secrets:
      clientId:
        required: true
      clientSecret:
        required: true
      tenantId:
        required: true
      subscriptionId:
        required: true    
jobs:
  create-compute:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.clientId }}","clientSecret":"${{ secrets.clientSecret }}","subscriptionId":"${{ secrets.subscriptionId }}","tenantId":"${{ secrets.tenantId }}"}'
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-compute-default-tier
        if: ${{( inputs.action_type == 'create' && inputs.cluster_tier == '')}}
        run: |
          az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type AmlCompute \
                                  --tier "dedicated" \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
      - name: create-compute-using-tier
        if: ${{( inputs.action_type == 'create' && inputs.cluster_tier != '')}}
        run: |
          az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type AmlCompute \
                                  --tier ${{ inputs.cluster_tier }} \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}        
      - name: delete-compute
        if: ${{ inputs.action_type == 'delete'}}
        run: |
          az ml compute delete --name ${{ inputs.cluster_name }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }} \
                                  --no-wait \
                                  --yes
